export default {
  WARNING: '⚠️ WARNING',
  INVALID_REPOSITORY: " it's an invalid git repository!",
  DESCRIPTION: 'CLI to view contributions of developers',
  WAITING: 'Please wait...',
  LONG_WAITING: 'It will take a few seconds for the first run, please wait',
  TOP: 'Top',
  NAME: 'Name',
  COMMITS: 'Commits',
  COMMITS_PERCENT: 'Commits percent',
  ADDITIONS: 'Additions',
  ADDITIONS_PERCENT: 'Additions percent',
  DELETIONS: 'Deletions',
  DELETIONS_PERCENT: 'Deletions percent',
  RANK_DESCRIPTION: 'rank of contributions',
  STATUS_DESCRIPTION: 'basic information of the repository',
  CLEAN_DESCRIPTION: 'clean the cache',
  CLEAN_TIP: '✅  clean the cache',
  RANK_T_DESCRIPTION: 'number of ranks,default is 10',
  RANK_SINCE_DESCRIPTION: 'Show ranks more recent than a specific date.',
  RANK_UNTIL_DESCRIPTION: 'Show ranks older than a specific date.',
  STATUS_SINCE_DESCRIPTION: 'Show status more recent than a specific date.',
  STATUS_UNTIL_DESCRIPTION: 'Show status older than a specific date.',
};
