export default {
  WARNING: '⚠️ 警告',
  INVALID_REPOSITORY: ' 当前目录为无效Git工程',
  DESCRIPTION: 'gb，一键查询代码贡献排名',
  WAITING: '请稍等...',
  LONG_WAITING: '首次初始化需要数秒，请稍等...',
  TITLE: '贡献前${top}名',
  TOP: 'Top',
  NAME: 'Name',
  COMMITS: 'Commits',
  COMMITS_PERCENT: 'Commits percent',
  ADDITIONS: 'Additions',
  ADDITIONS_PERCENT: 'Additions percent',
  DELETIONS: 'Deletions',
  DELETIONS_PERCENT: 'Deletions percent',
  RANK_DESCRIPTION: '一览贡献排名',
  STATUS_DESCRIPTION: '一览基本情况',
  CLEAN_DESCRIPTION: '清除缓存',
  CLEAN_TIP: '✅ 清除缓存',
  RANK_T_DESCRIPTION: '排名的位数，默认为10',
  RANK_SINCE_DESCRIPTION: '显示设定日期到现在的排名',
  RANK_UNTIL_DESCRIPTION: '显示直到设定日期的排名',
  STATUS_SINCE_DESCRIPTION: '显示设定日期到现在的状态',
  STATUS_UNTIL_DESCRIPTION: '显示直到设定日期的状态',
  REMOTE_URL: '　　远程网址',
  REMOTE_BRANCH: '　　远程分支',
  BEANCH: '　　本地分支',
  LAST_COMMIT: '最后提交时间',
  FIRST_COMMIT: '首次提交时间',
  LINES: '　　　总行数',
  CONTRIBUTORS: '　贡献者总计',
  STATUS_COMMITS: '　　提交次数',
  STATUS_ADDITIONS: '　　新增行数',
  STATUS_DELETIONS: '　　删除行数',
  STATUS_TITLE: '　　　项目',
  STATUS_VALUE: '　值',
};
