export default {
  WARNING: '⚠️ 警告',
  INVALID_REPOSITORY: ' 当前目录为无效Git工程',
  DESCRIPTION: 'gb，一键查询代码贡献排名',
  WAITING: '请稍等...',
  LONG_WAITING: '首次初始化需要数秒，请稍等...',
  TOP: '名次',
  NAME: '姓名',
  COMMITS: '提交次数',
  COMMITS_PERCENT: '提交次数占比',
  ADDITIONS: '新增行数',
  ADDITIONS_PERCENT: '新增行数占比',
  DELETIONS: '删除行数',
  DELETIONS_PERCENT: '删除行数占比',
  RANK_DESCRIPTION: '一览贡献排名',
  STATUS_DESCRIPTION: '一览基本情况',
  CLEAN_DESCRIPTION: '清除缓存',
  CLEAN_TIP: '✅ 清除缓存',
  RANK_T_DESCRIPTION: '排名的位数，默认为10',
  RANK_SINCE_DESCRIPTION: '显示设定日期到现在的排名',
  RANK_UNTIL_DESCRIPTION: '显示直到设定日期的排名',
  STATUS_SINCE_DESCRIPTION: '显示设定日期到现在的状态',
  STATUS_UNTIL_DESCRIPTION: '显示直到设定日期的状态',
};
